INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0001HST', 'POOJA VENKATESH', 'HOSTEL', DATE '2015-01-01', 'SUPERVISOR');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0001NTS', 'NAVYASHREE NAYAK', 'NON-TEACHING STAFF', DATE '2015-01-01', 'LAB ASSISTANT');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0002NTS', 'SHWETA SATHISH', 'NON-TEACHING STAFF', DATE '2015-01-01', 'LAB ASSISTANT');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0001SEC', 'KEERTHANA GANESH', 'SECURITY', DATE '2015-01-01', 'HEAD GUARD');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0002SEC', 'MOHAMMED SREENIVASA', 'SECURITY', DATE '2015-01-01', 'HEAD GUARD');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0003SEC', 'PROTTUSH JAYANTHI', 'SECURITY', DATE '2015-01-01', 'HEAD GUARD');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0004SEC', 'SHIVANI DEEPTHI', 'SECURITY', DATE '2015-01-01', 'HEAD GUARD');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0001TES', 'ADITYA SHAH', 'TEACHING STAFF', DATE '2015-01-01', 'ASSISTANT PROFESSOR');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0002TES', 'JAI JAIN', 'TEACHING STAFF', DATE '2015-01-01', 'ASSISTANT PROFESSOR');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0003TES', 'APOORVA SHETTY', 'TEACHING STAFF', DATE '2015-01-01', 'PROFESSOR');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0004TES', 'KALPAN BHATT', 'TEACHING STAFF', DATE '2015-01-01', 'PROFESSOR');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0005TES', 'KRISHNA AMIN', 'TEACHING STAFF', DATE '2015-01-01', 'PROFESSOR');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0006TES', 'PRANAV SHIRALAGI', 'TEACHING STAFF', DATE '2015-01-01', 'PROFESSOR');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0002HST', 'ANKIT CHOUDHARY', 'HOSTEL', DATE '2015-07-01', 'HOUSEKEEPING');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0003HST', 'DHANANJAYA BADRINATH', 'HOSTEL', DATE '2015-07-01', 'HOUSEKEEPING');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0004HST', 'GAYATHRI MEHRA', 'HOSTEL', DATE '2015-07-01', 'HOUSEKEEPING');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0005HST', 'SATHVIK NAVALE', 'HOSTEL', DATE '2015-07-01', 'HOUSEKEEPING');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0006HST', 'SANKIRTH UDUPA', 'HOSTEL', DATE '2015-07-01', 'SUPERVISOR');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0003NTS', 'AMOGHA RUDHRAN', 'NON-TEACHING STAFF', DATE '2015-07-01', 'HOUSEKEEPING');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0004NTS', 'HRIDYA ATHARV', 'NON-TEACHING STAFF', DATE '2015-07-01', 'HOUSEKEEPING');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0005NTS', 'KAUSHAL NARASIMHA', 'NON-TEACHING STAFF', DATE '2015-07-01', 'HOUSEKEEPING');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0006NTS', 'SHARAN JAYANTH', 'NON-TEACHING STAFF', DATE '2015-07-01', 'HOUSEKEEPING');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0007NTS', 'SHREYAS MUNVAR', 'NON-TEACHING STAFF', DATE '2015-07-01', 'HOUSEKEEPING');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0008NTS', 'SOMESH PATIL', 'NON-TEACHING STAFF', DATE '2015-07-01', 'HOUSEKEEPING');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0009NTS', 'AKSHATA VISHAK', 'NON-TEACHING STAFF', DATE '2015-07-01', 'LAB ASSISTANT');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0010NTS', 'NILANSHU SHAHAPURKAR', 'NON-TEACHING STAFF', DATE '2015-07-01', 'LAB ASSISTANT');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0011NTS', 'PRAGNA RAMYA', 'NON-TEACHING STAFF', DATE '2015-07-01', 'LAB ASSISTANT');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0005SEC', 'VISHNU FAROOQ', 'SECURITY', DATE '2015-07-01', 'HEAD GUARD');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0006SEC', 'SUDARSHAN KRISHNAMURTHY', 'SECURITY', DATE '2015-07-01', 'OFFICER');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0007SEC', 'VISWANATH JAIN', 'SECURITY', DATE '2015-07-01', 'OFFICER');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0007TES', 'KATTIRISETTY PATIL', 'TEACHING STAFF', DATE '2015-07-01', 'PROFESSOR');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0008TES', 'KRUTHIKA RAJU', 'TEACHING STAFF', DATE '2015-07-01', 'PROFESSOR');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0009TES', 'SHARAD SRIVASTAVA', 'TEACHING STAFF', DATE '2015-07-01', 'PROFESSOR');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0007HST', 'DARSHAN ADIGA', 'HOSTEL', DATE '2016-01-01', 'HOUSEKEEPING');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0008HST', 'GAGANA KUMAR', 'HOSTEL', DATE '2016-01-01', 'HOUSEKEEPING');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0009HST', 'HARIGOVIND DINESH', 'HOSTEL', DATE '2016-01-01', 'HOUSEKEEPING');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0010HST', 'BANDI MALLAPPA', 'HOSTEL', DATE '2016-01-01', 'SUPERVISOR');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0011HST', 'DIVISHA ASSADI', 'HOSTEL', DATE '2016-01-01', 'SUPERVISOR');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0012HST', 'JATIN ARJUN', 'HOSTEL', DATE '2016-01-01', 'SUPERVISOR');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0012NTS', 'ADITYA CHARAN', 'NON-TEACHING STAFF', DATE '2016-01-01', 'HOUSEKEEPING');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0013NTS', 'ARPANA RAJ', 'NON-TEACHING STAFF', DATE '2016-01-01', 'LAB ASSISTANT');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0014NTS', 'LIKHIT HEGADE', 'NON-TEACHING STAFF', DATE '2016-01-01', 'LAB ASSISTANT');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0015NTS', 'RITU ILYASI', 'NON-TEACHING STAFF', DATE '2016-01-01', 'LAB ASSISTANT');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0016NTS', 'VARSHA DEV', 'NON-TEACHING STAFF', DATE '2016-01-01', 'LAB ASSISTANT');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0008SEC', 'GAGANDHEEP PATEL', 'SECURITY', DATE '2016-01-01', 'HEAD GUARD');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0009SEC', 'TEJASHREE SUNKAVALLI', 'SECURITY', DATE '2016-01-01', 'OFFICER');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0010TES', 'BHUSHITH ANAND', 'TEACHING STAFF', DATE '2016-01-01', 'ASSISTANT PROFESSOR');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0011TES', 'SAPNA KUMAR', 'TEACHING STAFF', DATE '2016-01-01', 'PROFESSOR');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0012TES', 'SWAPNIL CHINCHUR', 'TEACHING STAFF', DATE '2016-01-01', 'PROFESSOR');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0013TES', 'VEDANSH RAO', 'TEACHING STAFF', DATE '2016-01-01', 'PROFESSOR');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0013HST', 'ANUSHA HEGDE', 'HOSTEL', DATE '2016-07-01', 'HOUSEKEEPING');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0014HST', 'PAVAN JALAN', 'HOSTEL', DATE '2016-07-01', 'HOUSEKEEPING');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0015HST', 'TARUN IYER', 'HOSTEL', DATE '2016-07-01', 'HOUSEKEEPING');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0016HST', 'AMAN BORANA', 'HOSTEL', DATE '2016-07-01', 'SUPERVISOR');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0017HST', 'MAHALAXMI SWATHI', 'HOSTEL', DATE '2016-07-01', 'SUPERVISOR');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0018HST', 'PRATEEK MENON', 'HOSTEL', DATE '2016-07-01', 'SUPERVISOR');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0017NTS', 'PRATHIK CHORADIA', 'NON-TEACHING STAFF', DATE '2016-07-01', 'HOUSEKEEPING');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0018NTS', 'VINAYAK SUD', 'NON-TEACHING STAFF', DATE '2016-07-01', 'HOUSEKEEPING');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0019NTS', 'ANANNYA ARSHAD', 'NON-TEACHING STAFF', DATE '2016-07-01', 'LAB ASSISTANT');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0020NTS', 'KAUSHAL PAVITRA', 'NON-TEACHING STAFF', DATE '2016-07-01', 'LAB ASSISTANT');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0021NTS', 'RASHMI KUMAR', 'NON-TEACHING STAFF', DATE '2016-07-01', 'LAB ASSISTANT');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0022NTS', 'SHIVANGI OMAR', 'NON-TEACHING STAFF', DATE '2016-07-01', 'LAB ASSISTANT');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0010SEC', 'ARUN TOSHNIWAL', 'SECURITY', DATE '2016-07-01', 'HEAD GUARD');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0011SEC', 'JAY MANSI', 'SECURITY', DATE '2016-07-01', 'HEAD GUARD');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0012SEC', 'SHRAVYA KIRAN', 'SECURITY', DATE '2016-07-01', 'HEAD GUARD');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0013SEC', 'SUBHASRI HASBI', 'SECURITY', DATE '2016-07-01', 'HEAD GUARD');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0014SEC', 'MAYUR SUKRUTA.N.', 'SECURITY', DATE '2016-07-01', 'OFFICER');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0015SEC', 'SHASHANK KALAHASTI', 'SECURITY', DATE '2016-07-01', 'OFFICER');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0014TES', 'CHETAN JAWADAGI', 'TEACHING STAFF', DATE '2016-07-01', 'PROFESSOR');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0019HST', 'MALAVIKA BHAT', 'HOSTEL', DATE '2017-01-01', 'HOUSEKEEPING');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0020HST', 'HEMANTH VIDYALAKSHMI', 'HOSTEL', DATE '2017-01-01', 'SUPERVISOR');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0023NTS', 'AKASH MALIPATIL', 'NON-TEACHING STAFF', DATE '2017-01-01', 'HOUSEKEEPING');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0024NTS', 'KARTHIK JOSHI', 'NON-TEACHING STAFF', DATE '2017-01-01', 'HOUSEKEEPING');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0016SEC', 'AVINASH RAO', 'SECURITY', DATE '2017-01-01', 'HEAD GUARD');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0017SEC', 'PRANAV SARANG', 'SECURITY', DATE '2017-01-01', 'HEAD GUARD');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0018SEC', 'SHARUN SUNDARAM', 'SECURITY', DATE '2017-01-01', 'OFFICER');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0015TES', 'ANARGHYA CHIKKANAGOUDA', 'TEACHING STAFF', DATE '2017-01-01', 'ASSISTANT PROFESSOR');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0016TES', 'VIGNESH MADHURA', 'TEACHING STAFF', DATE '2017-01-01', 'ASSISTANT PROFESSOR');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0017TES', 'BHARGAV KRITTIVASAN', 'TEACHING STAFF', DATE '2017-01-01', 'PROFESSOR');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0018TES', 'SAGAR PATIL', 'TEACHING STAFF', DATE '2017-01-01', 'PROFESSOR');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0021HST', 'ANJALI SHRIVIDHIYA', 'HOSTEL', DATE '2017-07-01', 'HOUSEKEEPING');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0022HST', 'HAREESH AJAY', 'HOSTEL', DATE '2017-07-01', 'HOUSEKEEPING');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0023HST', 'NAGASREE AASHISH', 'HOSTEL', DATE '2017-07-01', 'HOUSEKEEPING');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0024HST', 'NIKHIL NAAZ', 'HOSTEL', DATE '2017-07-01', 'HOUSEKEEPING');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0025HST', 'NIKKITHA VIKAS', 'HOSTEL', DATE '2017-07-01', 'SUPERVISOR');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0026HST', 'RUSHALI SRINIVAS', 'HOSTEL', DATE '2017-07-01', 'SUPERVISOR');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0027HST', 'SOORAJ KUMAR', 'HOSTEL', DATE '2017-07-01', 'SUPERVISOR');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0025NTS', 'AJITH SETTI', 'NON-TEACHING STAFF', DATE '2017-07-01', 'HOUSEKEEPING');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0026NTS', 'ARYA BHASIN', 'NON-TEACHING STAFF', DATE '2017-07-01', 'HOUSEKEEPING');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0027NTS', 'LAKSHYA SAWANT', 'NON-TEACHING STAFF', DATE '2017-07-01', 'HOUSEKEEPING');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0028NTS', 'ROHIT PRABHU', 'NON-TEACHING STAFF', DATE '2017-07-01', 'HOUSEKEEPING');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0029NTS', 'SWETHA GALUNDIA', 'NON-TEACHING STAFF', DATE '2017-07-01', 'HOUSEKEEPING');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0030NTS', 'AFEERA JANARDHAN', 'NON-TEACHING STAFF', DATE '2017-07-01', 'LAB ASSISTANT');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0031NTS', 'GOWTHAM C.R', 'NON-TEACHING STAFF', DATE '2017-07-01', 'LAB ASSISTANT');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0032NTS', 'NIHARIKA SHETTY', 'NON-TEACHING STAFF', DATE '2017-07-01', 'LAB ASSISTANT');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0033NTS', 'SHEETAL JAGADEESH', 'NON-TEACHING STAFF', DATE '2017-07-01', 'LAB ASSISTANT');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0034NTS', 'SRAVAN PATIL', 'NON-TEACHING STAFF', DATE '2017-07-01', 'LAB ASSISTANT');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0019SEC', 'ANUSREE MAIYA', 'SECURITY', DATE '2017-07-01', 'HEAD GUARD');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0020SEC', 'SAHANA ARPITHA', 'SECURITY', DATE '2017-07-01', 'HEAD GUARD');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0021SEC', 'ANUPRIYA JIROBE', 'SECURITY', DATE '2017-07-01', 'OFFICER');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0022SEC', 'SANTHOSH KAMATH', 'SECURITY', DATE '2017-07-01', 'OFFICER');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0019TES', 'JAGADEESH HARSHITA', 'TEACHING STAFF', DATE '2017-07-01', 'ASSISTANT PROFESSOR');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0020TES', 'KARTHIK GUMPENA', 'TEACHING STAFF', DATE '2017-07-01', 'ASSISTANT PROFESSOR');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0021TES', 'SHREYAS JAYARAM', 'TEACHING STAFF', DATE '2017-07-01', 'ASSISTANT PROFESSOR');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0022TES', 'ABHISHEK JOSEPH', 'TEACHING STAFF', DATE '2017-07-01', 'PROFESSOR');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0023TES', 'NITIN SHANBHOGUE', 'TEACHING STAFF', DATE '2017-07-01', 'PROFESSOR');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0028HST', 'AMRUTYA KADAM', 'HOSTEL', DATE '2018-01-01', 'HOUSEKEEPING');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0029HST', 'PREETI BIRADAR', 'HOSTEL', DATE '2018-01-01', 'HOUSEKEEPING');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0030HST', 'ROHIT JAIN', 'HOSTEL', DATE '2018-01-01', 'HOUSEKEEPING');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0031HST', 'ABHIJEET JAIN', 'HOSTEL', DATE '2018-01-01', 'SUPERVISOR');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0032HST', 'ANUSHA NAHENDER', 'HOSTEL', DATE '2018-01-01', 'SUPERVISOR');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0033HST', 'MEKHALA KASHYAP', 'HOSTEL', DATE '2018-01-01', 'SUPERVISOR');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0034HST', 'PAVAN VISHNU', 'HOSTEL', DATE '2018-01-01', 'SUPERVISOR');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0035NTS', 'PRAJWAL SOMNANI', 'NON-TEACHING STAFF', DATE '2018-01-01', 'HOUSEKEEPING');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0036NTS', 'SAJJAD GOWDA', 'NON-TEACHING STAFF', DATE '2018-01-01', 'HOUSEKEEPING');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0037NTS', 'SWAROOP ASHOK', 'NON-TEACHING STAFF', DATE '2018-01-01', 'HOUSEKEEPING');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0038NTS', 'KEERTHANA SUBRAMANYA', 'NON-TEACHING STAFF', DATE '2018-01-01', 'LAB ASSISTANT');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0039NTS', 'PRAVEEN.L. POOJA', 'NON-TEACHING STAFF', DATE '2018-01-01', 'LAB ASSISTANT');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0040NTS', 'SHREYAS VINAYAKA', 'NON-TEACHING STAFF', DATE '2018-01-01', 'LAB ASSISTANT');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0023SEC', 'HARSHA KUMAR', 'SECURITY', DATE '2018-01-01', 'HEAD GUARD');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0024SEC', 'RAGHAVAN MITTUR', 'SECURITY', DATE '2018-01-01', 'HEAD GUARD');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0024TES', 'AISHWARYA MANOJ', 'TEACHING STAFF', DATE '2018-01-01', 'ASSISTANT PROFESSOR');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0025TES', 'ARYAN RAMACHANDRAN', 'TEACHING STAFF', DATE '2018-01-01', 'ASSISTANT PROFESSOR');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0026TES', 'SRUSHTI SHETH', 'TEACHING STAFF', DATE '2018-01-01', 'ASSISTANT PROFESSOR');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0027TES', 'VARUN PATHAK', 'TEACHING STAFF', DATE '2018-01-01', 'ASSISTANT PROFESSOR');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0028TES', 'NISCHALA NEHA', 'TEACHING STAFF', DATE '2018-01-01', 'PROFESSOR');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0029TES', 'YASHWANTH MALLYA', 'TEACHING STAFF', DATE '2018-01-01', 'PROFESSOR');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0035HST', 'JAYANTH KUMARI', 'HOSTEL', DATE '2018-07-01', 'HOUSEKEEPING');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0036HST', 'NIKHIL NAYAK', 'HOSTEL', DATE '2018-07-01', 'HOUSEKEEPING');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0037HST', 'ROHAN KUMAR', 'HOSTEL', DATE '2018-07-01', 'HOUSEKEEPING');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0038HST', 'SHASHANK JAIN', 'HOSTEL', DATE '2018-07-01', 'HOUSEKEEPING');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0039HST', 'TUSHAR VENKATESH', 'HOSTEL', DATE '2018-07-01', 'HOUSEKEEPING');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0041NTS', 'JASMINE ADITI', 'NON-TEACHING STAFF', DATE '2018-07-01', 'HOUSEKEEPING');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0042NTS', 'JESTA JALAJ', 'NON-TEACHING STAFF', DATE '2018-07-01', 'HOUSEKEEPING');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0043NTS', 'RAHUL KRISHNA', 'NON-TEACHING STAFF', DATE '2018-07-01', 'HOUSEKEEPING');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0044NTS', 'DIVYAKRITI SHARMA', 'NON-TEACHING STAFF', DATE '2018-07-01', 'LAB ASSISTANT');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0045NTS', 'ROHITA MONARCH', 'NON-TEACHING STAFF', DATE '2018-07-01', 'LAB ASSISTANT');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0046NTS', 'TEJAS ANIRUDH', 'NON-TEACHING STAFF', DATE '2018-07-01', 'LAB ASSISTANT');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0047NTS', 'VIVEK SHETTY', 'NON-TEACHING STAFF', DATE '2018-07-01', 'LAB ASSISTANT');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0025SEC', 'PRATHYUSHA HEGDE', 'SECURITY', DATE '2018-07-01', 'HEAD GUARD');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0026SEC', 'TEJAS VIJAYA', 'SECURITY', DATE '2018-07-01', 'HEAD GUARD');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0027SEC', 'SHIVANITHYANATHAN DATTA', 'SECURITY', DATE '2018-07-01', 'OFFICER');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0030TES', 'DIVYAM SHANBHAG', 'TEACHING STAFF', DATE '2018-07-01', 'ASSISTANT PROFESSOR');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0031TES', 'MUKUND KULKARNI', 'TEACHING STAFF', DATE '2018-07-01', 'ASSISTANT PROFESSOR');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0032TES', 'NAMRATA JUNIAS', 'TEACHING STAFF', DATE '2018-07-01', 'ASSISTANT PROFESSOR');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0033TES', 'SIDDHANT PRASANNA', 'TEACHING STAFF', DATE '2018-07-01', 'ASSISTANT PROFESSOR');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0034TES', 'HRITIK BELLARY', 'TEACHING STAFF', DATE '2018-07-01', 'PROFESSOR');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0035TES', 'SHUBHAM REDDY', 'TEACHING STAFF', DATE '2018-07-01', 'PROFESSOR');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0036TES', 'TUSHAR MEHTA', 'TEACHING STAFF', DATE '2018-07-01', 'PROFESSOR');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0040HST', 'ANIRUDH PRAKASH', 'HOSTEL', DATE '2019-01-01', 'HOUSEKEEPING');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0041HST', 'ANVESH LAKAYIL', 'HOSTEL', DATE '2019-01-01', 'HOUSEKEEPING');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0042HST', 'BHARATH PERDOOR', 'HOSTEL', DATE '2019-01-01', 'HOUSEKEEPING');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0043HST', 'SHREYASH SINGH', 'HOSTEL', DATE '2019-01-01', 'HOUSEKEEPING');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0044HST', 'AYESHA UPPUNDA', 'HOSTEL', DATE '2019-01-01', 'SUPERVISOR');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0045HST', 'VAISHNAVI TANTRY', 'HOSTEL', DATE '2019-01-01', 'SUPERVISOR');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0046HST', 'VAISHRAVANA ANVEKAR', 'HOSTEL', DATE '2019-01-01', 'SUPERVISOR');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0048NTS', 'AMULYA JOTHINATHAN', 'NON-TEACHING STAFF', DATE '2019-01-01', 'HOUSEKEEPING');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0049NTS', 'TANUSHREE SURESH', 'NON-TEACHING STAFF', DATE '2019-01-01', 'HOUSEKEEPING');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0050NTS', 'AKHIL MALI', 'NON-TEACHING STAFF', DATE '2019-01-01', 'LAB ASSISTANT');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0051NTS', 'AYUSH PAMADI', 'NON-TEACHING STAFF', DATE '2019-01-01', 'LAB ASSISTANT');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0052NTS', 'KANAV GHATIKAR', 'NON-TEACHING STAFF', DATE '2019-01-01', 'LAB ASSISTANT');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0053NTS', 'MANU SUCHITH', 'NON-TEACHING STAFF', DATE '2019-01-01', 'LAB ASSISTANT');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0054NTS', 'PRAJNA NAYAK', 'NON-TEACHING STAFF', DATE '2019-01-01', 'LAB ASSISTANT');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0055NTS', 'SIDDANAGOUDA SHRIRAKSHA', 'NON-TEACHING STAFF', DATE '2019-01-01', 'LAB ASSISTANT');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0028SEC', 'RITESH PARAG', 'SECURITY', DATE '2019-01-01', 'HEAD GUARD');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0029SEC', 'DARRYL SOUMYA', 'SECURITY', DATE '2019-01-01', 'OFFICER');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0030SEC', 'REKHA HEGDE', 'SECURITY', DATE '2019-01-01', 'OFFICER');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0031SEC', 'RITWIK ANSHU', 'SECURITY', DATE '2019-01-01', 'OFFICER');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0037TES', 'ANISH JAIN', 'TEACHING STAFF', DATE '2019-01-01', 'ASSISTANT PROFESSOR');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0038TES', 'CHIRANJAN SHARMA', 'TEACHING STAFF', DATE '2019-01-01', 'ASSISTANT PROFESSOR');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0039TES', 'MAITHRI RANJAN', 'TEACHING STAFF', DATE '2019-01-01', 'ASSISTANT PROFESSOR');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0040TES', 'AMOGH RAHUL', 'TEACHING STAFF', DATE '2019-01-01', 'PROFESSOR');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0041TES', 'ANIRUDH MITTUR', 'TEACHING STAFF', DATE '2019-01-01', 'PROFESSOR');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0042TES', 'RAMYA AGARWAL', 'TEACHING STAFF', DATE '2019-01-01', 'PROFESSOR');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0043TES', 'SRIVATSA ANMOL', 'TEACHING STAFF', DATE '2019-01-01', 'PROFESSOR');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0044TES', 'VINEETA RAO', 'TEACHING STAFF', DATE '2019-01-01', 'PROFESSOR');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0047HST', 'ISHTARTH NERELLA', 'HOSTEL', DATE '2019-07-01', 'HOUSEKEEPING');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0048HST', 'KEVIN SRINIVASAN', 'HOSTEL', DATE '2019-07-01', 'HOUSEKEEPING');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0049HST', 'MAHIMA KULKARNI', 'HOSTEL', DATE '2019-07-01', 'HOUSEKEEPING');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0050HST', 'MANASA BYAKOD', 'HOSTEL', DATE '2019-07-01', 'HOUSEKEEPING');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0051HST', 'NISHITHA UPADHYAYA', 'HOSTEL', DATE '2019-07-01', 'HOUSEKEEPING');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0052HST', 'PAVITHRA BHARATH', 'HOSTEL', DATE '2019-07-01', 'HOUSEKEEPING');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0053HST', 'YASHAS VADHYAR', 'HOSTEL', DATE '2019-07-01', 'HOUSEKEEPING');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0054HST', 'SAHANA SHASHANK', 'HOSTEL', DATE '2019-07-01', 'SUPERVISOR');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0055HST', 'SAI CHAUHAN', 'HOSTEL', DATE '2019-07-01', 'SUPERVISOR');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0056NTS', 'AMOGHA MASAUN', 'NON-TEACHING STAFF', DATE '2019-07-01', 'HOUSEKEEPING');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0057NTS', 'KUSUMA NAIDU', 'NON-TEACHING STAFF', DATE '2019-07-01', 'LAB ASSISTANT');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0032SEC', 'ANIRUDH DESAI', 'SECURITY', DATE '2019-07-01', 'HEAD GUARD');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0033SEC', 'KAUSHIK GRANDHE', 'SECURITY', DATE '2019-07-01', 'OFFICER');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0045TES', 'SANJAY SRINIVASAN', 'TEACHING STAFF', DATE '2019-07-01', 'ASSISTANT PROFESSOR');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0046TES', 'SUBRAMANYA KANTHI', 'TEACHING STAFF', DATE '2019-07-01', 'ASSISTANT PROFESSOR');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0047TES', 'MEGHNA SONAR', 'TEACHING STAFF', DATE '2019-07-01', 'PROFESSOR');
INSERT INTO staff_info(employee_id, name, type, join_date, designation) VALUES('0048TES', 'PRANAV MAHAVEER', 'TEACHING STAFF', DATE '2019-07-01', 'PROFESSOR');
